### ISSUE TITLE
Class cast exception when using language injections

### ISSUE THREAD

**Issue by Flynamic** [antlr/antlr4-intellij-adaptor#24]
When injecting my language into other file types such as XML or JSON, the IDE throws an error everytime I type:

` class com.intellij.psi.impl.source.xml.XmlTextImpl cannot be cast to class org.antlr.intellij.adaptor.psi.ScopeNode
java.lang.ClassCastException: class com.intellij.psi.impl.source.xml.XmlTextImpl cannot be cast to class org.antlr.intellij.adaptor.psi.ScopeNode (com.intellij.psi.impl.source.xml.XmlTextImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @67b64c45; org.antlr.intellij.adaptor.psi.ScopeNode is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5466ba6)
	at org.antlr.intellij.adaptor.SymtabUtils.getContextFor(SymtabUtils.java:51)
	at org.antlr.intellij.adaptor.psi.ANTLRPsiNode.getContext(ANTLRPsiNode.java:53)
	at org.antlr.intellij.adaptor.psi.ANTLRPsiNode.getContext(ANTLRPsiNode.java:31)
	at org.antlr.intellij.adaptor.SymtabUtils.getContextFor(SymtabUtils.java:51)
	at org.antlr.intellij.adaptor.psi.ANTLRPsiNode.getContext(ANTLRPsiNode.java:53)
	at org.antlr.intellij.adaptor.psi.ANTLRPsiNode.getContext(ANTLRPsiNode.java:31)
	at org.antlr.intellij.adaptor.SymtabUtils.getContextFor(SymtabUtils.java:51)
	at org.antlr.intellij.adaptor.psi.ANTLRPsiNode.getContext(ANTLRPsiNode.java:53)
	at org.antlr.intellij.adaptor.psi.ANTLRPsiNode.getContext(ANTLRPsiNode.java:31)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:570)
	at com.intellij.lang.javascript.intentions.JSIntroduceVariableIntention.findExpression(JSIntroduceVariableIntention.java:149)
	at com.intellij.lang.javascript.intentions.JSIntroduceVariableIntention.isAvailable(JSIntroduceVariableIntention.java:180)
	...
`

This seems to get triggered by JavaScript code insights.

**Comment by parrt** [comment]
Hi. Thanks for reporting. I'm just now starting to get back into the plug in stuff after many years so might take me a while to get to this.
