### ISSUE TITLE
`java.lang.IndexOutOfBoundsException` in `ANTLRLexerAdaptor.toLexerState`

### ISSUE THREAD

**Issue by ris58h** [antlr/antlr4-intellij-adaptor#31]
It happens for injected languages when `startOffset` is not zero and `initialState` is zero. In this case `stateCache` is empty and we get:

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at org.antlr.intellij.adaptor.lexer.ANTLRLexerAdaptor.toLexerState(ANTLRLexerAdaptor.java:280)
	at org.antlr.intellij.adaptor.lexer.ANTLRLexerAdaptor.start(ANTLRLexerAdaptor.java:168)
	at com.intellij.lexer.HtmlHighlightingLexer$XmlEmbeddmentHandler.handleElement(HtmlHighlightingLexer.java:269)
	at com.intellij.lexer.BaseHtmlLexer.advance(BaseHtmlLexer.java:415)
	at com.intellij.lexer.HtmlHighlightingLexer.advance(HtmlHighlightingLexer.java:173)
```

**Comment by ris58h** [comment]
I've ended up with a [hack](https://github.com/ris58h/WebCalm/blob/90ae35510e0a06889326c4e1b764b6a3533d1fd6/src/main/kotlin/ris58h/webcalm/antlr/FixedANTLRLexerAdaptor.kt) to work around the issue but I'm not sure if it's a right way to fix it.
